### PR TITLE
Implement transfer via address book, without styles

### PR DESCRIPTION
**Pull request by mrmaDrma**
This pull request resolves issue #74 

Its still not finished, since I need design

@Krakaw

### CODE REVIEW

**Comment by simple-taskic** [comment]
Hey @mileTadic1994 can you explain what is missing from UI side?

**Comment by mileTadic1994** [comment]
[Here](https://github.com/big-neon/bn-mobile-react/issues/74#issuecomment-502015488) is detailed explanation about what is required from design

**Comment by Tas4tari** [comment]
@mileTadic1994 Based on @Krakaw message on GitHub, why has the issue been blacked, is there anything else other than his response that you require

**Comment by Tas4tari** [comment]
https://app.zenhub.com/workspaces/big-neon-engineering-5c8c172f5df6d54b7b12500c/issues/big-neon/bn-mobile-react/74

**Comment by Krakaw** [comment]
@mileTadic1994 Please see this comment, just follow the design here: https://github.com/big-neon/bn-mobile-react/issues/74#issuecomment-505340581

**Comment by mileTadic1994** [comment]
> Pressing the address book button crashes the app on my android device.
> 
> [20190703_140513.mp4.zip](https://github.com/big-neon/bn-mobile-react/files/3354872/20190703_140513.mp4.zip)

Weird, it didn't pop contact list permission at all ?

**Comment by mileTadic1994** [comment]
> Pressing the address book button crashes the app on my android device.
> 
> [20190703_140513.mp4.zip](https://github.com/big-neon/bn-mobile-react/files/3354872/20190703_140513.mp4.zip)

@Krakaw 
Can you please confirm this issue ? 
[2019_07_04_15_50_55.mp4.tar.gz](https://github.com/big-neon/bn-mobile-react/files/3359596/2019_07_04_15_50_55.mp4.tar.gz)

**Comment by mileTadic1994** [comment]
@simple-taskic 
Can you also take a look at this and maybe help me improve this?

**Comment by Krakaw** [comment]
> > Pressing the address book button crashes the app on my android device.
> > [20190703_140513.mp4.zip](https://github.com/big-neon/bn-mobile-react/files/3354872/20190703_140513.mp4.zip)
> 
> @Krakaw
> Can you please confirm this issue ?
> [2019_07_04_15_50_55.mp4.tar.gz](https://github.com/big-neon/bn-mobile-react/files/3359596/2019_07_04_15_50_55.mp4.tar.gz)

Is that on a real device?

**Comment by mileTadic1994** [comment]
> > > Pressing the address book button crashes the app on my android device.
> > > [20190703_140513.mp4.zip](https://github.com/big-neon/bn-mobile-react/files/3354872/20190703_140513.mp4.zip)
> > 
> > 
> > @Krakaw
> > Can you please confirm this issue ?
> > [2019_07_04_15_50_55.mp4.tar.gz](https://github.com/big-neon/bn-mobile-react/files/3359596/2019_07_04_15_50_55.mp4.tar.gz)
> 
> Is that on a real device?

Yeah, that's from my phone.
Platform: Android 9.0, Device: Samsung J6+

**Comment by Krakaw** [comment]
Looks good, let's fix the conflict and it can go in for QA

**Comment by Krakaw** [comment]
The functionality looks good, just noticed the different line shadings, is it possible to get the grid uniform?
Screenshot_20190801-074912__01

**Comment by mrmaDrma** [comment]
> The functionality looks good, just noticed the different line shadings, is it possible to get the grid uniform?
> Screenshot_20190801-074912__01

Is this better?

export

**Comment by Krakaw** [comment]
Much better

**Pull request merged**
