### PR TITLE
Improve attendee list swipe UX

### PR DESCRIPTION
**Pull request by coka**
### References Issues:

https://app.asana.com/0/1149047845558135/1149033169772094

### Description:

The threshold for what constitutes a check-in swipe action has been lowered. Partially swiping will reveal the option on the left, and allow check-in by manually pressing the pink button.

### CODE REVIEW

**Comment by Krakaw** [comment]
Can we adjust the action to only take place once the finger has been released? If I swipe to the right, then swipe back to the left, the check in action might have already taken place.

**Comment by Krakaw** [comment]
The whole screen refreshes every time a guest is checked in. Can we inline update only the affected rows.
You can use the `changes_since` parameter in the guests.index query to only get the changes you do not have. http://github.com/big-neon/bn-mobile-react/blob/8e5e61979de803f3141fb8738a98b17be6e84521/src/state/eventManagerStateProvider.js#L39-L39

**Comment by coka** [comment]
@Tas4tari and I have agreed to put this on hold due to other priorities.

Also, there are a few outstanding questions from my side, both from a product, as well as from a technical perspective.

**Comment by coka** [comment]
@mikethetike Since @Krakaw's comment, the following changes have been made:

* A row can be swiped in from both sides now, and hard swiping is no longer supported. The removal of hard swiping has been approved by Robin. This means that the button has to be pressed after revealing it.
* The attendee list doesn't refresh after every check-in. I'm leaving the `changes_since` bit for the live update ticket.
* Styles now more closely match what's in the design, and some satellite UX stuff (such as keyboard dismissal) has been resolved along the way.
* Code naming still mixes "guest" and "attendee", but we're incrementally moving to "attendee".

Merging now would move the swipe UX ticket to QA, and enable me to work on other attendee list tickets without making this PR any bigger than it needs to be.

**Pull request merged**
