### PR TITLE
Back button in view ticket incorrectly navigating to scanner

### PR DESCRIPTION
**Pull request by mileTadic1994**
Fixes : https://github.com/big-neon/bn-mobile-react/issues/49

Back button logic moved to the proper component in order to navigate through app flow.

### CODE REVIEW

**Comment by mileTadic1994** [comment]
> When I click the back menu item it is escaping all the way to the scanner. It should be going to the guest list.
> http://cl.ly/22651f0b915d

Yea, but this button still says 'Scan ticket', so maybe we should also change that label ?

**Comment by Krakaw** [comment]
You can change the label to `Guest List`

**Comment by mileTadic1994** [comment]
> When I click the back menu item it is escaping all the way to the scanner. It should be going to the guest list.
> http://cl.ly/22651f0b915d

Currently, Quest List is not a single component and its not regular navigation screen (it is just a part of the Scanner screen). Back menu is connected to navigation and can only navigate between navigation screens, so there is problem returning to quest list. I talked with @simple-taskic and he said he will also take a look and try to find the best and easiest way to fix this.

**Comment by simple-taskic** [comment]
Hey @Krakaw @mileTadic1994 please take another look at this PR, I think I have found some decent solution.

**Pull request merged**
